step0_repl: step0_repl.c
	gcc -std=c99 -Wall -Werror -o step0_repl step0_repl.c

step1_repl: step1_repl.c
	gcc -std=c99 -Wall -Werror -o step1_repl step1_repl.c

clean:
	rm -f step0_repl step1_repl

.PHONY: clean
